import FoodScan from '../../screens/nutrition_logs/food_scan/FoodScan';

export const NavigatorNames = {
  main: 'Main',
  home: 'Home',
  profile: 'Profile',
  splash: 'Splash',
  signUp: 'SignUp',
  signIn: 'SignIn',
  forgotPassword: 'ForgotPassword',
  resetPassword: 'ResetPassword',
  otpAuth: 'OtpAuth',
  myReports: 'My Reports',
  message: 'Message',
  accountCreated: 'AccountCreated',
  authentication: 'Authentication',
  foodLog: 'FoodLog',
  addFood: 'AddFood',
  personalInfo: 'PersonalInfo',
  archive: 'Archive',
  devices: 'Devices',
  searchArchive: 'SearchArchive',
  privacyNotice: 'PrivacyNotice',
  termsOfUse: 'TermsOfUse',
  barCodeScan: 'BarCodeScan',
  addIngredient: 'AddIngredient',
  ingredientDetails: 'IngredientDetails',
  foodScan: 'FoodScan',
  searchFood: 'SearchFood',
  logFood: 'LogFood',
  movementList: 'MovementList',
  surveyList: 'SurveyList',
  surveyWebView: 'SurveyWebView',
  videoInstructions: 'VideoInstructions',
  setupVideoInstructions: 'SetupVideoInstructions',
  patientList: 'PatientList',
  uploadAllVideo: 'UploadAllVideo',
  mocapView: 'MocapView',
  hcpMovementList: 'HcpMovementList',
  healthData: 'HealthData',
  hcpProfile: 'HcpProfile',
  mocapPlayBack: 'MocapPlayBack',
  connectedDevices: 'ConnectedDevices',
  receipeCardNew: 'ReceipeCardNew',
  devicesWebView: 'DevicesWebView'
} as const;
