# Resolve react_native_pods.rb with node to allow for hoisting
def node_require(script)
  # Resolve script with node to allow for hoisting
  require Pod::Executable.execute_command('node', ['-p',
    "require.resolve(
      '#{script}',
      {paths: [process.argv[1]]},
    )", __dir__]).strip
end

node_require('react-native/scripts/react_native_pods.rb')
node_require('react-native-permissions/scripts/setup.rb')

platform :ios, '15.5'
prepare_react_native_project!
setup_permissions([
  # 'AppTrackingTransparency',
    'Microphone',
   'Camera',
   'SpeechRecognition'
   
  ])

use_frameworks! :linkage => :static

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'ameya' do
  config = use_native_modules!
  pod 'RNFS', :path => '../node_modules/react-native-fs'
  pod 'KeychainAccess'

  # Enable Hermes engine for better performance and lower memory consumption
  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true, # Ensure Hermes is enabled
    :fabric_enabled => true,
    :app_path => "#{Pod::Config.instance.installation_root}/..",
  )

  target 'ameyaTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
  end
end
